title: HRT Cat

theme: just-the-docs
color_scheme: dark
logo: "/assets/images/logo.png"

url: https://hrt.cat

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue

mermaid:
  # https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
