title: HRT Cat

theme: just-the-docs
color_scheme: dark
logo: "/assets/images/logo.png"

url: https://hrt.cat

callouts:
  warning:
    title: Warning
    color: red
  caution:
      title: Caution
      color: yellow
  info:
    title: Info
    color: blue
  notice:
    title: Notice
    color: green

mermaid:
  # https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
